### PR TITLE
Minor updates to docker

### PR DESCRIPTION
**Pull request by JeremyCraigMartinez**
Processes in the container are extremely slow. Looks like it is [an issue currently under develop](https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/271)

### CODE REVIEW

**Comment by benfjohnson** [comment]
I haven't been able to get the app to run in docker with these changes -- are there any additional steps beyond `npm run docker-build` and `npm run docker-run`? I may merge my PR as-is to make sure our teammates in India aren't blocked overnight, but we'll definitely need to incorporate these changes once I can get them building, as rebuilding the container after each code change is incredibly inefficient.

**Comment by JeremyCraigMartinez** [comment]
looking into it now

**Comment by JeremyCraigMartinez** [comment]
what is the error you're seeing?

**Comment by benfjohnson** [comment]
Pulled it down, works great

**Pull request merged**
